/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo_penjualan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sudiy
 */
public class Penjualan extends javax.swing.JFrame {
    
    private DefaultTableModel tabel_penjualan;
    private String query;
    
    public void tampilkanData(){
        tabel_penjualan = new DefaultTableModel();
        tabel_penjualan.addColumn("ID Transaksi");
        tabel_penjualan.addColumn("Nama Customer");
        tabel_penjualan.addColumn("Nama Produk");
        tabel_penjualan.addColumn("Harga");
        tabel_penjualan.addColumn("Jumlah");
        tabel_penjualan.addColumn("Total");
        
        penjualanTBL.setModel(tabel_penjualan);
        
        Connection c = koneksi.getKoneksi();
        try{
            Statement s = c.createStatement();
            query = "SELECT * FROM transaksi";
            ResultSet r = s.executeQuery(query);
            
            while(r.next()){
                tabel_penjualan.addRow(new Object[]{
                    r.getString("ID_Transaksi"),
                    r.getString("Nama"),
                    r.getString("Nama_Produk"),
                    r.getString("Harga"),
                    r.getString("Jumlah"),
                    r.getString("Total"),
                });
            }
        } catch(SQLException e){
            System.out.println(e);
        }
    }
    
    private void kosongkanData(){
        IDTransaksiTF.setText("");
        NamaTF.setText("");
        NamaProdukTF.setText("");
        HargaTF.setText("");
        JumlahTF.setText("");
        TotalTF1.setText("");
    }

    /**
     * Creates new form Penjualan
     */
    public Penjualan() {
        initComponents();
        this.tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        IDTransaksiTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NamaTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NamaProdukTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        HargaTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JumlahTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TotalTF1 = new javax.swing.JTextField();
        SimpanBTN = new javax.swing.JButton();
        EditBTN = new javax.swing.JButton();
        HapusBTN = new javax.swing.JButton();
        BatalBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        penjualanTBL = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Nova Cond", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENJUALAN BAJU");

        jLabel2.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KELOMPOK 2");

        jLabel3.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("4A SISTEM INFORMASI");

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Transaksi");

        IDTransaksiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTransaksiTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");

        NamaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaTFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Produk");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jumlah");

        JumlahTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahTFActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total");

        TotalTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTF1ActionPerformed(evt);
            }
        });

        SimpanBTN.setText("Simpan");
        SimpanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanBTNActionPerformed(evt);
            }
        });

        EditBTN.setText("Edit");
        EditBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBTNActionPerformed(evt);
            }
        });

        HapusBTN.setText("Hapus");
        HapusBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBTNActionPerformed(evt);
            }
        });

        BatalBTN.setText("Batal");
        BatalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalBTNActionPerformed(evt);
            }
        });

        penjualanTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Transaksi", "Nama", "Nama Produk", "Harga", "Jumlah", "Total"
            }
        ));
        penjualanTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penjualanTBLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(penjualanTBL);

        jLabel10.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DATA PENJUALAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDTransaksiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JumlahTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaProdukTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SimpanBTN)
                    .addComponent(BatalBTN)
                    .addComponent(EditBTN)
                    .addComponent(HapusBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDTransaksiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SimpanBTN))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(EditBTN))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(HapusBTN)
                        .addGap(7, 7, 7)
                        .addComponent(BatalBTN))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(NamaProdukTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(HargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(JumlahTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TotalTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTransaksiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTransaksiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTransaksiTFActionPerformed

    private void NamaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaTFActionPerformed

    private void EditBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBTNActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getKoneksi();
            String query = "UPDATE transaksi SET Nama = '"+NamaTF.getText()+"', Nama_Produk = '"+NamaProdukTF.getText()+"',"
                    + " Harga = '"+HargaTF.getText()+"', Jumlah = '"+JumlahTF.getText()+"', Total = '"+TotalTF1.getText()+"'"
                    + " WHERE ID_Transaksi = '"+IDTransaksiTF.getText()+"'";
            PreparedStatement ps = c.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah");
        }
        
        tampilkanData();
        kosongkanData();
    }//GEN-LAST:event_EditBTNActionPerformed

    private void SimpanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanBTNActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getKoneksi();
            String query = "INSERT INTO transaksi VALUES('"+IDTransaksiTF.getText()+"','"+NamaTF.getText()+"',"
                    + "'"+NamaProdukTF.getText()+"','"+HargaTF.getText()+"','"+JumlahTF.getText()+"','"+TotalTF1.getText()+"')";
            PreparedStatement ps = c.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
            
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal disimpan");
        }
        
        tampilkanData();
        kosongkanData();
    }//GEN-LAST:event_SimpanBTNActionPerformed

    private void BatalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalBTNActionPerformed
        // TODO add your handling code here:
        kosongkanData();
    }//GEN-LAST:event_BatalBTNActionPerformed

    private void HapusBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBTNActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = koneksi.getKoneksi();
            String query = "DELETE FROM transaksi WHERE ID_Transaksi = '"+IDTransaksiTF.getText()+"'";
            PreparedStatement ps = c.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
            
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal dihapus");
        }
        
        tampilkanData();
        kosongkanData();
    }//GEN-LAST:event_HapusBTNActionPerformed

    private void JumlahTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahTFActionPerformed
        // TODO add your handling code here:
        if(HargaTF != null && JumlahTF != null){
            int harga = Integer.parseInt(HargaTF.getText());
            int jumlah = Integer.parseInt(JumlahTF.getText());
            int total = harga * jumlah;
            
            TotalTF1.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_JumlahTFActionPerformed

    private void TotalTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTF1ActionPerformed

    private void penjualanTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualanTBLMouseClicked
        // TODO add your handling code here:
        int baris = penjualanTBL.rowAtPoint(evt.getPoint());
        String idtrans = penjualanTBL.getValueAt(baris, 0).toString();
        IDTransaksiTF.setText(idtrans);
        String nama = penjualanTBL.getValueAt(baris, 1).toString();
        NamaTF.setText(nama);
        String namaProduk = penjualanTBL.getValueAt(baris, 2).toString();
        NamaProdukTF.setText(namaProduk);
        String harga = penjualanTBL.getValueAt(baris, 3).toString();
        HargaTF.setText(harga);
        String jumlah = penjualanTBL.getValueAt(baris, 4).toString();
        JumlahTF.setText(jumlah);
        String total = penjualanTBL.getValueAt(baris, 5).toString();
        TotalTF1.setText(total);
    }//GEN-LAST:event_penjualanTBLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalBTN;
    private javax.swing.JButton EditBTN;
    private javax.swing.JButton HapusBTN;
    private javax.swing.JTextField HargaTF;
    private javax.swing.JTextField IDTransaksiTF;
    private javax.swing.JTextField JumlahTF;
    private javax.swing.JTextField NamaProdukTF;
    private javax.swing.JTextField NamaTF;
    private javax.swing.JButton SimpanBTN;
    private javax.swing.JTextField TotalTF1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable penjualanTBL;
    // End of variables declaration//GEN-END:variables
}
